security:
  basic:
    enabled: false

management:
  security:
    enabled: false

logging:
  level:
    io:
      pivotal: INFO

greeting:
  displayFortune: false

quoteServiceURL: http://quote-service-dev.apps.dev.na-1.gaia.jpmchase.net/quote