security:
  basic:
    enabled: false

management:
  security:
    enabled: false

logging:
  level:
    io:
      pivotal: DEBUG

greeting:
  displayFortune: true
  xyz: sang

quoteServiceURL: http://quote-server-sang-shin-qa.cfapps.io/quote